colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
showScrollToTop = true
showBreadcrumbs = true

[homepage]
  layout = "card"
  showRecent = true
  showRecentItems = 6
  cardView = true
  cardViewScreenWidth = false

[article]
  showSummary = true
  showTableOfContents = false

[list]
  showCards = true
  groupByYear = false
  cardView = true
